name: Go test tsshd
on: [push]
jobs:
  go-test-on-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tsshd
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: go test
        run: go test -v -count=1 ./tsshd
  go-test-on-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout tsshd
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: go test
        run: go test -v -count=1 ./tsshd
  go-test-on-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout tsshd
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: go test
        run: go test -v -count=1 ./tsshd
  go-release-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tsshd
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v1"
          args: release --clean --snapshot --skip=publish
  test-win7-go1_20:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tsshd
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - name: Build tsshd
        run: |
          sed -i 's/go 1\.21/go 1.20/g' go.mod
          go get github.com/xtaci/kcp-go/v5@v5.6.1 github.com/quic-go/quic-go@v0.40.1
          go mod tidy
          go test -v -tags win7 -count=1 ./tsshd
          GOOS=windows GOARCH=386 go build -tags win7 -o tsshd_win7_i386/ ./cmd/tsshd/
          GOOS=windows GOARCH=amd64 go build -tags win7 -o tsshd_win7_x86_64/ ./cmd/tsshd/
