name: Release and publish tsshd
on:
  release:
    types: [released]
jobs:
  release-and-publish:
    name: Release and publish tsshd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tsshd
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --skip=publish
      - name: Upload Release Assets
        uses: trzsz/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ github.event.release.id }}
          assets_path: |
            dist/*.tar.gz
            dist/*.zip
            dist/*.rpm
            dist/*_checksums.txt
      - name: Publish rpm to Gemfury
        env:
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
        run: |
          for filename in dist/tsshd*.rpm; do
            curl -F package=@"$filename" https://{$FURY_TOKEN}@push.fury.io/trzsz/
          done
